### PR TITLE
Dossier scenario import

### PR DESCRIPTION
**Pull request by adrienlachaize**
Administrators are able to download “dossier” content into eight different .xlsx layouts.

### CODE REVIEW

**Comment by BertrandBordage** [comment]
Hello Adrien!

Very nice to see this first contribution to the Dezède codebase by someone else than me :smile: 
I see you used some of the undocumented APIs I created for exports & static files grouping. I hope it wasn’t too hard to figure out! I guess not, given that you didn’t contact me about it :)

I had an overall look at your PR, it seems great! I didn’t test it yet.
Is it ready for test & review? Since you created then closed another PR, I’m wondering.

**Comment by adrienlachaize** [comment]
Hi Bertrand,
Sorry for the late answer. Yes, you can review this merge request.
Let me know if you have any question.

**Comment by BertrandBordage-zoetis** [comment]
There are a few minor issues, especially with localization. I also didn’t understand at first what “Data not available” meant when I looked at the exported files. I changed it to “Season not available”. I also simplified the code a bit because a good part of it was repeated.

Since I cannot push on your fork, I’m going to merge this PR then add a new commit afterwards.

**Comment by BertrandBordage** [comment]
There are a few minor issues, especially with localization. I also didn’t understand at first what “Data not available” meant when I looked at the exported files. I changed it to “Season not available”. I also simplified the code a bit because a good part of it was repeated.

Since I cannot push on your fork, I’m going to merge this PR then add a new commit afterwards.

**Pull request merged**
